repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Basics
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

      # Specific files
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: check-xml
