[project]
name = "movie-organizer"
version = "0.1.0"
description = "A utility to organize movie metadata and assets"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-fasthtml>=0.12.20",
]
